fix stationgovernor.lua errors
Error: "Property not found or not readable: Entity.hasCaptain"
Also not needed because it already checks directly below if a captain is there.

Error: "stationgovernor.lua:49: attempt to call global 'random' (a nil value)"
Added "include ("randomext")" because of that